### ISSUE TITLE
equivalent of ephem az,el to ra,dec

### ISSUE THREAD

**Issue by zonca** [brandon-rhodes/python-skyfield#13]
a vectorized version of `ephem` is a great idea!

I have this simple az,el to ra,dec conversion, could you please help me to translate it using `skyfield`?

```python
observer = ephem.Observer()
observer.lon = lon
observer.lat = lat
observer.elevation = alt
observer.date = utc
print observer.radec_of(azimuth, elevation)
```

**Comment by cdeil** [comment]
@brandon-rhodes FYI - Astropy now can do AltAz to RaDec and we've started testing against other packages, e.g. PyEphem here (https://github.com/astropy/coordinates-benchmark/blob/master/coordinates_benchmark/tools/pyephem.py#L62).

I don't plan to add SkyField myself, but it would certainly be welcome (see https://github.com/astropy/coordinates-benchmark/blob/master/docs/Tools.rst#skyfield).

**Comment by brandon-rhodes** [comment]
I have implemented a simple version of altaz-to-radec conversion! Observer locations produced by the `topos()` call and computed for a specific date now support a `from_altaz()` method. I am going to continue sprucing up the API through the evening, but it does work:

    jd = JulianDate(tt=2440423.345833333)
    usno = de405.earth.topos('38.9215 N', '77.0669 W', elevation_m=92.0)
    a = usno(jd).from_altaz(alt_degrees=68.12871390985195, az_degrees=28.97924422088555)
    ra, dec, distance = a.radec(epoch=jd)

To try it out before the next version of Skyfield is released, simply install directly from GitHub:

    pip install https://github.com/brandon-rhodes/python-skyfield/archive/master.zip
